## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew --version; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew add gcc; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install hdf5; fi

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait 20 julia --project=docs/ docs/make.jl
      after_success: skip
