## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - nightly
notifications:
  email: false
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
script:
  - "travis_wait 30 julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'"
addons:
  apt:
    packages:
    - libgfortran3
    - libglu1
    - libxcursor1
    - libxrender1
    - libxft2
    - libxinerama1
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  # include:
    # - stage: "Documentation"
    #   julia: 1.4
    #   os: linux
    #   install:
    #     # mkdocs-material isn't available at the default py2 on travis-ci for now
    #     - sudo apt-get update
    #     - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda config --set always_yes yes --set changeps1 no
    #     - conda update -q conda
    #     - conda info -a
    #   script:
    #     - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
    #     - julia --project=docs --color=yes docs/make.jl
    #   after_success: skip
