language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notification:
  email: false
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("JuEQ"); Pkg.test("JuEQ"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("JuEQ")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
