site_name:        'JuEQ.jl'
site_description: 'Julia implementations of earthquake cycle simulation'
site_author:      'Pengcheng Shi'
site_url:         'https://github.com/shipengcheng1230/JuEQ.jl'

repo_name:        'JuEQ.jl'
repo_url:         'https://github.com/shipengcheng1230/JuEQ.jl'

copyright: 'Copyright &copy; 2018 - 2019 <a href="https://github.com/shipengcheng1230/JuEQ.jl">Pengcheng Shi</a>'

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo:
    icon: 'landscape'

extra:
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/shipengcheng1230'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/pengcheng-shi-396960148'
    - type: 'steam'
      link: 'https://steamcommunity.com/profiles/76561198054638928/'
    - type: 'xbox'
      link: 'https://live.xbox.com/en-US/Profile?Gamertag=ElyseesKukushka'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - toc:
      permalink: true
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition
  - footnotes
  - pymdownx.highlight:
      css_class: codehilite
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde

docs_dir: 'build'

nav:
  - Home: 'index.md'
  - 'Quasi Dynamic Simulation using BEM':
    - 'Example 1D': 'examples/generated/bp1.md'
    - 'Example 2D': 'examples/generated/otfsync.md'
  - Interface:
    - Assemble: 'interface_assemble.md'
    - Friction: 'interface_friction.md'
    - Greens Function: 'interface_greensfun.md'
    - HDF5 Utility: 'interface_HDF5.md'
    - Mesh: 'interface_mesh.md'
    - Simulation Property: 'interface_property.md'
    - Rheology: 'interface_rheology.md'
    - Visualize: 'interface_visualize.md'
  - Acknowledge: 'acknowledge.md'
